### ISSUE TITLE
Sugestion 

### ISSUE THREAD

**Issue by filoor** [matteocargnelutti/jean-pierre#5]
Hi,

My idea is to add supermarket so that you can see which supermarket you can buy it 
So if let say i go to AH("a supermarket in the Netherlands") i can filter on that.
Some prod will be available in mulltiple markets.
When you add a new product you can chose which supermarket you did buy it (or can buy it)

I don't know if i can do that so maybe i will need some help from you if you like the idea.

I will receive my raspberry tomorrow 
Will try to start in the weekend on it

**Comment by matteocargnelutti** [comment]
Hi,

Jean-Pierre is based on the OpenFoodFacts API, which provides this information : it has a field that contains, for a given product, the names of the stores in which you can buy it.

More information on this : https://world.openfoodfacts.org/data

But the main issue with that feature is its reliability : the information is never really accurate. 
Mainly because it has to be given and updated by users, but also because different stores within a supermarket chain don't necesarily sell the same products. 

Have fun with Jean-Pierre :) !

**Comment by filoor** [comment]
Thank you for the info
